### ISSUE TITLE
host argument not working

### ISSUE THREAD

**Issue by w0ofy** [tolu/mkcert-cli#13]
Hey there! First things first — want to extend my thanks and appreciation for decoupling this from vite and wrapping `mkcert` into a comprehensible cli tool.

## The potential bug
Passing `--host` doesn't work. I believe it's because `hosts` isn't passed to `createCertificate` in `cli.js`.

## The ask
Is this intended? Or can this be fixed? Thanks in advance for your help!

**Comment by tolu** [comment]
sorr for the delay, should be fixed via #14
